# Exceptions in Lua
no `try-catch`!

# Protected call
Protected call doesn't terminate the execution

    suc, y = pcall(f, -5)